import 'dotenv/config'
import { getPayload } from 'payload'
import config from '@payload-config'

import {
  RETIRED_CUISINE_SLUGS,
  SEED_AUTHORS,
  SEED_BRAND_CARDS,
  SEED_CUISINES,
  SEED_RECIPES,
} from './data'
import { placeholderImage } from './placeholderImage'
import { slugify } from '../fields/slug'

/**
 * Idempotent development seed. Safe to re-run: everything is matched on slug or
 * name and updated in place rather than duplicated.
 *
 * This does NOT produce the launch catalog (§3, §9) — see the warning printed
 * at the end.
 */

const payload = await getPayload({ config })

/** Lexical needs a real document tree, not a bare string. */
function richText(text: string) {
  return {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      direction: 'ltr' as const,
      children: [
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          direction: 'ltr' as const,
          children: [{ type: 'text', text, format: 0, style: '', mode: 'normal', detail: 0, version: 1 }],
        },
      ],
    },
  }
}

async function upsertMedia(alt: string, palette: [string, string], seed: string) {
  const existing = await payload.find({
    collection: 'media',
    where: { alt: { equals: alt } },
    limit: 1,
  })
  if (existing.docs[0]) return existing.docs[0].id

  const file = await placeholderImage({ from: palette[0], to: palette[1], seed })
  const doc = await payload.create({
    collection: 'media',
    data: {
      alt,
      credit: 'PLACEHOLDER — generated by the dev seed. Replace before launch (§11 Q4).',
      license: 'original',
    },
    file: {
      data: file,
      mimetype: 'image/jpeg',
      name: `${slugify(seed)}.jpg`,
      size: file.byteLength,
    },
  })
  return doc.id
}

async function upsert<T extends 'cuisines' | 'authors' | 'recipes' | 'brandCards'>(
  collection: T,
  where: Record<string, unknown>,
  data: Record<string, unknown>,
) {
  const existing = await payload.find({ collection, where: where as never, limit: 1 })
  if (existing.docs[0]) {
    const updated = await payload.update({
      collection,
      id: existing.docs[0].id,
      data: data as never,
    })
    return updated
  }
  return payload.create({ collection, data: data as never })
}

console.log('Seeding cuisines…')
const cuisineIds = new Map<string, string | number>()
for (const c of SEED_CUISINES) {
  const heroImage = await upsertMedia(`${c.name} cuisine`, c.palette, `cuisine-${c.name}`)
  const doc = await upsert(
    'cuisines',
    { slug: { equals: slugify(c.name) } },
    {
      name: c.name,
      slug: slugify(c.name),
      region: c.region,
      flagEmoji: c.flagEmoji,
      description: c.description,
      heroImage,
    },
  )
  cuisineIds.set(c.name, doc.id)
}

console.log('Seeding authors…')
const authorIds = new Map<string, string | number>()
for (const a of SEED_AUTHORS) {
  const doc = await upsert(
    'authors',
    { slug: { equals: slugify(a.name) } },
    { name: a.name, slug: slugify(a.name), bio: a.bio, provenanceDefault: a.provenanceDefault },
  )
  authorIds.set(a.name, doc.id)
}
const defaultAuthor = authorIds.get(SEED_AUTHORS[0].name)!

console.log('Seeding recipes…')
const recipeIds = new Map<string, string | number>()
for (const r of SEED_RECIPES) {
  const heroImage = await upsertMedia(r.title, r.palette, `recipe-${r.title}`)
  const doc = await upsert(
    'recipes',
    { slug: { equals: slugify(r.title) } },
    {
      title: r.title,
      slug: slugify(r.title),
      heroImage,
      story: r.story ? richText(r.story) : undefined,
      servings: r.servings,
      ingredients: r.ingredients,
      steps: r.steps,
      cuisine: cuisineIds.get(r.cuisine),
      course: r.course,
      mainIngredient: r.mainIngredient,
      spiciness: r.spiciness,
      sweetness: r.sweetness,
      richness: r.richness,
      effort: r.effort,
      dietaryTags: r.dietaryTags,
      prepMinutes: r.prepMinutes,
      cookMinutes: r.cookMinutes,
      difficulty: r.difficulty,
      nutrition: r.nutrition,
      provenance: 'authored',
      author: defaultAuthor,
      status: 'published',
    },
  )
  recipeIds.set(r.title, doc.id)
}

console.log('Seeding brand cards…')
for (const b of SEED_BRAND_CARDS) {
  const logo = await upsertMedia(`${b.brand} logo`, b.palette, `brand-${b.brand}`)
  await upsert(
    'brandCards',
    { brand: { equals: b.brand } },
    {
      brand: b.brand,
      tagline: b.tagline,
      ctaLabel: b.ctaLabel,
      ctaUrl: b.ctaUrl,
      logo,
      productImage: logo,
      weight: b.weight,
      active: true,
      targetRegions: b.targetRegions.map((code) => ({ code })),
      assignedCuisines: b.assignedCuisines
        .map((name) => cuisineIds.get(name))
        .filter((id): id is string | number => id !== undefined),
      // Explicitly clear any recipe-level assignments from earlier seed shapes.
      assignedRecipes: [],
    },
  )
}

// Cuisines retired from the taxonomy (folded into broader hubs). Recipes and
// brand cards have already been re-pointed above, so these docs are now
// orphans — remove them so stale hubs don't linger in navigation or the sitemap.
for (const slug of RETIRED_CUISINE_SLUGS) {
  const stale = await payload.find({ collection: 'cuisines', where: { slug: { equals: slug } }, limit: 1 })
  if (stale.docs[0]) {
    await payload.delete({ collection: 'cuisines', id: stale.docs[0].id })
    console.log(`Retired cuisine: ${slug}`)
  }
}

const adminEmail = process.env.SEED_ADMIN_EMAIL
const adminPassword = process.env.SEED_ADMIN_PASSWORD
if (adminEmail && adminPassword) {
  const existing = await payload.find({
    collection: 'users',
    where: { email: { equals: adminEmail } },
    limit: 1,
  })
  if (!existing.docs[0]) {
    await payload.create({
      collection: 'users',
      data: { email: adminEmail, password: adminPassword },
    })
    console.log(`Created admin user ${adminEmail}`)
  }
}

console.log(`
Seed complete — ${SEED_RECIPES.length} recipes, ${SEED_CUISINES.length} cuisines, ${SEED_BRAND_CARDS.length} brand cards.

⚠️  This is sample content, not the launch catalog.
    · Design spec §3 requires 30-50 recipes that a human has cooked and verified.
      These are marked provenance: authored so the authored path is exercised,
      but nobody has tested them. Do not publish this to a real domain as-is.
    · Every image is a generated placeholder credited as such (§11 Q4 is open).
`)

process.exit(0)
