/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    recipes: Recipe;
    ingredients: Ingredient;
    cuisines: Cuisine;
    authors: Author;
    brandCards: BrandCard;
    media: Media;
    submissions: Submission;
    partnerRequests: PartnerRequest;
    adEvents: AdEvent;
    groceryRetailers: GroceryRetailer;
    groceryEvents: GroceryEvent;
    ratings: Rating;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    cuisines: CuisinesSelect<false> | CuisinesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    brandCards: BrandCardsSelect<false> | BrandCardsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    partnerRequests: PartnerRequestsSelect<false> | PartnerRequestsSelect<true>;
    adEvents: AdEventsSelect<false> | AdEventsSelect<true>;
    groceryRetailers: GroceryRetailersSelect<false> | GroceryRetailersSelect<true>;
    groceryEvents: GroceryEventsSelect<false> | GroceryEventsSelect<true>;
    ratings: RatingsSelect<false> | RatingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  title: string;
  /**
   * Food photography is the product. This one is not optional.
   */
  heroImage: number | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Short notes, capped at 120 words. Renders *below* the recipe — never blocks the cook.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional long-form Story in Markdown (supports images). Shown behind a Story toggle that replaces the instructions — opt-in, never the default.
   */
  storyMarkdown?: string | null;
  /**
   * Images referenced by the Story markdown (hosted here so links never rot).
   */
  storyImages?: (number | Media)[] | null;
  servings: number;
  ingredients: {
    quantity?: string | null;
    unit?: string | null;
    item: string;
    /**
     * e.g. "finely diced", "room temperature"
     */
    note?: string | null;
    /**
     * This row is a section label ("To serve", "For the sauce"), not an ingredient. Skipped by matching, the shopping list, and nutrition.
     */
    heading?: boolean | null;
    /**
     * Optional key linking this ingredient to an affiliate product. Phase 1 stores it; Phase 2 resolves it.
     */
    affiliateKey?: string | null;
    /**
     * Auto-linked canonical ingredient.
     */
    ingredient?: (number | null) | Ingredient;
    needsReview?: boolean | null;
    id?: string | null;
  }[];
  steps: {
    text: string;
    image?: (number | null) | Media;
    /**
     * Optional. Renders an inline timer for this step.
     */
    timerSeconds?: number | null;
    /**
     * Canonical ingredients this step uses.
     */
    uses?: (number | Ingredient)[] | null;
    id?: string | null;
  }[];
  /**
   * Optional. Shown on cooking mode’s finish screen — storage, reheating, and what the leftovers become.
   */
  finish?: {
    /**
     * Days it keeps refrigerated.
     */
    storageDays?: number | null;
    /**
     * e.g. "Low heat with a splash of water."
     */
    reheat?: string | null;
    /**
     * What tomorrow’s lunch becomes.
     */
    leftoverIdeas?: string | null;
  };
  /**
   * Optional. A creator’s TikTok/YouTube/Reels/Vimeo link — embedded on the recipe page. Set automatically when a creator submission is approved.
   */
  videoUrl?: string | null;
  /**
   * Mise-en-place pins on the hero photo — a short kicker + note, hidden on the page until a reader hovers or taps. Place them visually on the photo above; add, remove, and label them here.
   */
  heroAnnotations?:
    | {
        /**
         * % from left
         */
        x: number;
        /**
         * % from top
         */
        y: number;
        /**
         * Short label, e.g. “Yolk”.
         */
        kicker: string;
        /**
         * One line, e.g. “Pull at 6 min — jammy, not set.”
         */
        note: string;
        id?: string | null;
      }[]
    | null;
  cuisine: number | Cuisine;
  course: 'breakfast' | 'lunch' | 'dinner' | 'side' | 'snack' | 'dessert';
  /**
   * What the dish is built on — the shopping-list headline.
   */
  mainIngredient:
    | 'chicken'
    | 'beef'
    | 'pork'
    | 'lamb'
    | 'seafood'
    | 'eggs'
    | 'tofu-tempeh'
    | 'legumes'
    | 'vegetables'
    | 'rice-grains'
    | 'pasta-noodles'
    | 'cheese-dairy'
    | 'duck'
    | 'turkey'
    | 'mushrooms'
    | 'potatoes'
    | 'bread-dough'
    | 'chocolate-sweets'
    | 'fruit'
    | 'squash-pumpkin'
    | 'corn-maize'
    | 'plantains-cassava';
  /**
   * 0 = No heat, 5 = Fiery
   */
  spiciness: number;
  /**
   * 0 = Savoury, 5 = Dessert-sweet
   */
  sweetness: number;
  /**
   * 0 = Clean, 5 = Decadent
   */
  richness: number;
  /**
   * 0 = Effortless, 5 = A project
   */
  effort: number;
  dietaryTags?:
    | (
        | 'vegan'
        | 'vegetarian'
        | 'pescatarian'
        | 'gluten-free'
        | 'dairy-free'
        | 'nut-free'
        | 'egg-free'
        | 'low-carb'
        | 'keto'
        | 'paleo'
        | 'whole30'
        | 'halal'
        | 'kosher'
        | 'low-fodmap'
        | 'sugar-free'
        | 'high-protein'
        | 'low-sodium'
        | 'soy-free'
        | 'shellfish-free'
      )[]
    | null;
  prepMinutes: number;
  cookMinutes: number;
  /**
   * Derived from prep + cook.
   */
  totalMinutes?: number | null;
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * Pence (GBP) per serving — the seed/estimates are authored in pence; prices render with £.
   */
  costPerServing?: number | null;
  /**
   * Kitchen-reality filter: what a cook needs to make this.
   */
  equipment?:
    | (
        | 'stovetop'
        | 'oven'
        | 'microwave'
        | 'grill'
        | 'blender'
        | 'food-processor'
        | 'slow-cooker'
        | 'air-fryer'
        | 'no-cook'
      )[]
    | null;
  /**
   * Cooks in a single pan/pot.
   */
  onePan?: boolean | null;
  /**
   * Can be partly or fully made in advance.
   */
  makeAhead?: boolean | null;
  /**
   * Optional. Feeds Recipe JSON-LD when present.
   */
  nutrition?: {
    calories?: number | null;
    /**
     * grams
     */
    protein?: number | null;
    /**
     * grams
     */
    carbs?: number | null;
    /**
     * grams
     */
    fat?: number | null;
    /**
     * grams
     */
    saturates?: number | null;
    /**
     * grams
     */
    sugars?: number | null;
    /**
     * grams
     */
    fibre?: number | null;
    /**
     * grams
     */
    salt?: number | null;
    /**
     * Estimated grams per serving — derives per-100g values for FSA traffic lights.
     */
    servingGrams?: number | null;
  };
  /**
   * Optional curator override (1–5). Leave blank to show the community average — we don’t seed ratings.
   */
  editorialRating?: number | null;
  /**
   * Number of community votes. Maintained by the rate endpoint.
   */
  ratingCount?: number | null;
  /**
   * Sum of community stars (average = sum ÷ count).
   */
  ratingSum?: number | null;
  /**
   * Derived: editorial override, else community average, else 0. Drives sort & filter.
   */
  ratingScore?: number | null;
  /**
   * Load-bearing (§3): drives trust badges, filtering, and Google transparency.
   */
  provenance: 'authored' | 'community' | 'api-imported';
  author: number | Author;
  /**
   * Required for api-imported recipes — imported content is duplicate content across the web and must carry canonical attribution (§3, §8).
   */
  sourceAttribution?: {
    sourceName?: string | null;
    sourceUrl?: string | null;
  };
  /**
   * Optional direct assignment. Cards can also become eligible via their own cuisine/recipe targeting.
   */
  brandSlots?: (number | BrandCard)[] | null;
  /**
   * Falls back to the recipe title.
   */
  metaTitle?: string | null;
  /**
   * Falls back to the first line of the story.
   */
  metaDescription?: string | null;
  /**
   * Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically on first publish.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the dish for screen readers and for Google Images.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source. Required for anything not shot in-house.
   */
  credit?: string | null;
  license?: ('original' | 'licensed' | 'ai-generated' | 'partner') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  /**
   * Other names that map here.
   */
  aliases?: string[] | null;
  category?:
    | ('produce' | 'dairy' | 'protein' | 'oil-fat' | 'grain-legume' | 'spice-herb' | 'condiment' | 'bakery' | 'other')
    | null;
  /**
   * Discrete items (eggs, cloves).
   */
  countable?: boolean | null;
  substitutions?:
    | {
        sub?: (number | null) | Ingredient;
        /**
         * Free-text sub when not a catalog ingredient.
         */
        subText?: string | null;
        kind: 'flavor' | 'texture' | 'cupboard';
        /**
         * e.g. "1:1", "use ¾".
         */
        ratio?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — enables weight⇄volume for tsp/tbsp/ml/cup. Defaults to ~1 (water) when blank.
   */
  densityGPerMl?: number | null;
  /**
   * Average grams for one piece — 1 egg ≈ 50, 1 clove garlic ≈ 3, 1 onion ≈ 110. Enables count / “no unit” quantities.
   */
  gramsPerPiece?: number | null;
  nutrition?: {
    kcalPer100g?: number | null;
    proteinPer100g?: number | null;
    carbsPer100g?: number | null;
    fatPer100g?: number | null;
    saturatesPer100g?: number | null;
    sugarsPer100g?: number | null;
    fibrePer100g?: number | null;
    saltPer100g?: number | null;
    /**
     * USDA food matched at seed time.
     */
    source?: string | null;
  };
  price?: {
    /**
     * In pence, GBP — the baseline is authored in one currency on purpose. A cook shopping elsewhere records their own prices; we never convert, because a made-up exchange rate is worse than saying we do not know.
     */
    packPrice?: number | null;
    /**
     * How much is in that pack: 500, 750, 12.
     */
    packAmount?: number | null;
    /**
     * Pieces skips the weight conversion entirely — "12 eggs for £3" needs no grams-per-egg.
     */
    packUnit?: ('g' | 'ml' | 'piece') | null;
    /**
     * The shop and product it was read off, e.g. "Tesco Olive Oil 500ml". A price nobody can trace is a guess wearing a number — this is what makes it checkable.
     */
    source?: string | null;
    /**
     * Groceries move. This is how you find the prices that have gone stale rather than re-checking all of them.
     */
    checkedAt?: string | null;
  };
  needsReview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines".
 */
export interface Cuisine {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  region:
    | 'east-asia'
    | 'south-asia'
    | 'southeast-asia'
    | 'middle-east'
    | 'africa'
    | 'northern-europe'
    | 'southern-europe'
    | 'eastern-europe'
    | 'north-america'
    | 'latin-america'
    | 'caribbean'
    | 'oceania'
    | 'cross-regional';
  /**
   * Optional. Used as a lightweight glyph where a hero image would be too heavy.
   */
  flagEmoji?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * One or two sentences. Doubles as the cuisine hub meta description.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  /**
   * Supabase user id — the stable key that ties a creator to their profile.
   */
  creatorId?: string | null;
  /**
   * Public @handle shown on recipes and the creator profile.
   */
  handle?: string | null;
  /**
   * Editorial trust mark — grant manually once you know the creator is real.
   */
  verified?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Short profile bio (max 160 chars). Creators can edit their own from /account.
   */
  bio?: string | null;
  /**
   * Public social links. Creators can edit their own from /account.
   */
  socials?: {
    /**
     * Full URL, e.g. https://instagram.com/handle
     */
    instagram?: string | null;
    /**
     * Full URL, e.g. https://tiktok.com/@handle
     */
    tiktok?: string | null;
    /**
     * Full URL, e.g. https://youtube.com/@channel
     */
    youtube?: string | null;
    /**
     * Full URL, e.g. https://x.com/handle
     */
    x?: string | null;
    /**
     * Full URL, e.g. https://yoursite.com
     */
    website?: string | null;
  };
  /**
   * Provenance applied to new recipes by this author unless overridden on the recipe itself.
   */
  provenanceDefault: 'authored' | 'community' | 'api-imported';
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-curated partner placements. Swapping a card in or out is a CMS edit — rotation stays fair automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandCards".
 */
export interface BrandCard {
  id: number;
  brand: string;
  /**
   * The brand mark. One per brand — used when a creative has no image of its own.
   */
  logo?: (number | null) | Media;
  /**
   * One or more images for this campaign. Several are rotated evenly per visitor, so a brand can run a set rather than a single picture, and a tired creative can be retired without pausing the card. Leave empty to fall back to the brand logo.
   */
  creatives?:
    | {
        image: number | Media;
        /**
         * Optional line for THIS image. Leave empty to use the campaign tagline below.
         */
        tagline?: string | null;
        /**
         * Retire one image without touching the rest of the campaign.
         */
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy single image. Cards created before creatives existed still render from this; prefer Creatives above.
   */
  productImage?: (number | null) | Media;
  /**
   * One line. This is a card, not a banner.
   */
  tagline: string;
  ctaLabel: string;
  /**
   * Affiliate or partner destination. Rendered with rel="sponsored nofollow".
   */
  ctaUrl: string;
  /**
   * ISO country codes (GB, US, DE…). Leave empty to target globally.
   */
  targetRegions?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Card is eligible on any recipe in these cuisines.
   */
  assignedCuisines?: (number | Cuisine)[] | null;
  /**
   * Card is eligible on these specific recipes.
   */
  assignedRecipes?: (number | Recipe)[] | null;
  /**
   * Percent of this card’s revenue shared with the recipe’s creator. Baseline 50 (platform keeps 50).
   */
  revSharePercent?: number | null;
  /**
   * Revenue in cents per 1,000 impressions (CPM). Drives estimated creator earnings. 0 until a real rate is agreed with the partner.
   */
  cpmCents?: number | null;
  /**
   * Relative share of impressions in the rotation. 2 is shown twice as often as 1. 0 disables without deactivating.
   */
  weight: number;
  active?: boolean | null;
  /**
   * Optional. Card is ineligible before this moment.
   */
  startsAt?: string | null;
  /**
   * Optional. Card is ineligible after this moment.
   */
  endsAt?: string | null;
  /**
   * Stop serving after this many impressions. Empty means no cap. A flight that can only be ended by a date or by remembering to switch it off is not a campaign you control — this is how a fixed buy stops itself.
   */
  maxImpressions?: number | null;
  /**
   * Counted from the impression log. Read-only.
   */
  impressionsServed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Creator submissions from /studio. Approve to publish; promotion is automatic.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title: string;
  /**
   * Food photography is the product. This one is not optional.
   */
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Short notes, capped at 120 words. Renders *below* the recipe — never blocks the cook.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional long-form Story in Markdown (supports images). Shown behind a Story toggle that replaces the instructions — opt-in, never the default.
   */
  storyMarkdown?: string | null;
  /**
   * Images referenced by the Story markdown (hosted here so links never rot).
   */
  storyImages?: (number | Media)[] | null;
  servings: number;
  ingredients: {
    quantity?: string | null;
    unit?: string | null;
    item: string;
    /**
     * e.g. "finely diced", "room temperature"
     */
    note?: string | null;
    /**
     * This row is a section label ("To serve", "For the sauce"), not an ingredient. Skipped by matching, the shopping list, and nutrition.
     */
    heading?: boolean | null;
    /**
     * Optional key linking this ingredient to an affiliate product. Phase 1 stores it; Phase 2 resolves it.
     */
    affiliateKey?: string | null;
    /**
     * Auto-linked canonical ingredient.
     */
    ingredient?: (number | null) | Ingredient;
    needsReview?: boolean | null;
    id?: string | null;
  }[];
  steps: {
    text: string;
    image?: (number | null) | Media;
    /**
     * Optional. Renders an inline timer for this step.
     */
    timerSeconds?: number | null;
    /**
     * Canonical ingredients this step uses.
     */
    uses?: (number | Ingredient)[] | null;
    id?: string | null;
  }[];
  /**
   * Optional. Shown on cooking mode’s finish screen — storage, reheating, and what the leftovers become.
   */
  finish?: {
    /**
     * Days it keeps refrigerated.
     */
    storageDays?: number | null;
    /**
     * e.g. "Low heat with a splash of water."
     */
    reheat?: string | null;
    /**
     * What tomorrow’s lunch becomes.
     */
    leftoverIdeas?: string | null;
  };
  cuisine: number | Cuisine;
  course: 'breakfast' | 'lunch' | 'dinner' | 'side' | 'snack' | 'dessert';
  /**
   * What the dish is built on — the shopping-list headline.
   */
  mainIngredient:
    | 'chicken'
    | 'beef'
    | 'pork'
    | 'lamb'
    | 'seafood'
    | 'eggs'
    | 'tofu-tempeh'
    | 'legumes'
    | 'vegetables'
    | 'rice-grains'
    | 'pasta-noodles'
    | 'cheese-dairy'
    | 'duck'
    | 'turkey'
    | 'mushrooms'
    | 'potatoes'
    | 'bread-dough'
    | 'chocolate-sweets'
    | 'fruit'
    | 'squash-pumpkin'
    | 'corn-maize'
    | 'plantains-cassava';
  /**
   * 0 = No heat, 5 = Fiery
   */
  spiciness: number;
  /**
   * 0 = Savoury, 5 = Dessert-sweet
   */
  sweetness: number;
  /**
   * 0 = Clean, 5 = Decadent
   */
  richness: number;
  /**
   * 0 = Effortless, 5 = A project
   */
  effort: number;
  dietaryTags?:
    | (
        | 'vegan'
        | 'vegetarian'
        | 'pescatarian'
        | 'gluten-free'
        | 'dairy-free'
        | 'nut-free'
        | 'egg-free'
        | 'low-carb'
        | 'keto'
        | 'paleo'
        | 'whole30'
        | 'halal'
        | 'kosher'
        | 'low-fodmap'
        | 'sugar-free'
        | 'high-protein'
        | 'low-sodium'
        | 'soy-free'
        | 'shellfish-free'
      )[]
    | null;
  prepMinutes: number;
  cookMinutes: number;
  /**
   * Derived from prep + cook.
   */
  totalMinutes?: number | null;
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * Pence (GBP) per serving — the seed/estimates are authored in pence; prices render with £.
   */
  costPerServing?: number | null;
  /**
   * Kitchen-reality filter: what a cook needs to make this.
   */
  equipment?:
    | (
        | 'stovetop'
        | 'oven'
        | 'microwave'
        | 'grill'
        | 'blender'
        | 'food-processor'
        | 'slow-cooker'
        | 'air-fryer'
        | 'no-cook'
      )[]
    | null;
  /**
   * Cooks in a single pan/pot.
   */
  onePan?: boolean | null;
  /**
   * Can be partly or fully made in advance.
   */
  makeAhead?: boolean | null;
  /**
   * Optional. Feeds Recipe JSON-LD when present.
   */
  nutrition?: {
    calories?: number | null;
    /**
     * grams
     */
    protein?: number | null;
    /**
     * grams
     */
    carbs?: number | null;
    /**
     * grams
     */
    fat?: number | null;
    /**
     * grams
     */
    saturates?: number | null;
    /**
     * grams
     */
    sugars?: number | null;
    /**
     * grams
     */
    fibre?: number | null;
    /**
     * grams
     */
    salt?: number | null;
    /**
     * Estimated grams per serving — derives per-100g values for FSA traffic lights.
     */
    servingGrams?: number | null;
  };
  /**
   * Supabase user id of the creator who submitted this.
   */
  creatorId?: string | null;
  creatorName?: string | null;
  creatorEmail?: string | null;
  creatorHandle?: string | null;
  /**
   * The creator’s account avatar at submission time.
   */
  creatorAvatar?: (number | null) | Media;
  /**
   * Optional TikTok/YouTube/Reels link — creators are video-first.
   */
  videoUrl?: string | null;
  /**
   * Set automatically when approved.
   */
  promotedRecipe?: (number | null) | Recipe;
  /**
   * Set when a creator edits an existing recipe. On approval, that recipe is updated in place rather than a new one created.
   */
  editsRecipe?: (number | null) | Recipe;
  moderationStatus: 'pending' | 'approved' | 'rejected';
  /**
   * Sent to the creator verbatim when you reject. Say what would fix it — this is the human part of "reviewed by a person".
   */
  moderationNote?: string | null;
  /**
   * Legacy Payload-admin submitter link — unused for creator submissions. The real submitter is in Creator name / handle / email above (Supabase account).
   */
  submittedBy?: (number | null) | User;
  /**
   * Contact for the submitter before accounts exist.
   */
  submitterEmail?: string | null;
  /**
   * Internal. Why this was approved or rejected.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Advertising requests from /partners. Approve to scaffold an inactive draft brand card, then add creative and activate it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerRequests".
 */
export interface PartnerRequest {
  id: number;
  company: string;
  /**
   * Becomes the brand card’s destination (rel="sponsored nofollow").
   */
  website: string;
  contactName: string;
  contactEmail: string;
  /**
   * What they want to advertise — seeds the card tagline.
   */
  promoting: string;
  /**
   * ISO country codes (US, GB, KR…) they want to reach. Empty = global.
   */
  targetRegions?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  budgetRange?: ('under-500' | '500-2k' | '2k-10k' | '10k-plus' | 'not-sure') | null;
  message?: string | null;
  status: 'pending' | 'approved' | 'declined';
  /**
   * Draft card created on approval.
   */
  scaffoldedCard?: (number | null) | BrandCard;
  /**
   * Internal. Why this was approved or declined.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Impression/click log behind creator earnings. Written automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adEvents".
 */
export interface AdEvent {
  id: number;
  kind: 'impression' | 'click';
  brandCard: number | BrandCard;
  recipe: number | Recipe;
  updatedAt: string;
  createdAt: string;
}
/**
 * Where "Shop this list" sends people, by country. Add affiliate templates as programs get approved — links work without them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groceryRetailers".
 */
export interface GroceryRetailer {
  id: number;
  label: string;
  /**
   * Stable id for links and seeds, e.g. "tesco".
   */
  slug: string;
  type: 'supermarket' | 'delivery' | 'marketplace';
  /**
   * ISO codes (GB, US, DE…). Leave empty to show everywhere.
   */
  countries?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search URL with {query}, e.g. https://www.tesco.com/groceries/en-GB/search?query={query}
   */
  searchUrlTemplate: string;
  /**
   * Optional wrapper with {url}, e.g. https://www.awin1.com/cread.php?awinmid=…&ued={url}. Leave empty until the program is approved.
   */
  affiliateUrlTemplate?: string | null;
  network?: ('none' | 'awin' | 'amazon' | 'other') | null;
  /**
   * Higher shows first.
   */
  priority: number;
  active?: boolean | null;
  notes?: string | null;
  impressions?: number | null;
  clicks?: number | null;
  /**
   * Click-through %, all time.
   */
  ctr?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Impression/click log behind Shop this list. Written automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groceryEvents".
 */
export interface GroceryEvent {
  id: number;
  kind: 'impression' | 'click';
  retailer: number | GroceryRetailer;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community star ratings — one per user per recipe. Written by the rate endpoint; the recipe’s average is kept in sync there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ratings".
 */
export interface Rating {
  id: number;
  recipe: number | Recipe;
  /**
   * Supabase user id of the rater.
   */
  userId: string;
  stars: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'cuisines';
        value: number | Cuisine;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'brandCards';
        value: number | BrandCard;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'partnerRequests';
        value: number | PartnerRequest;
      } | null)
    | ({
        relationTo: 'adEvents';
        value: number | AdEvent;
      } | null)
    | ({
        relationTo: 'groceryRetailers';
        value: number | GroceryRetailer;
      } | null)
    | ({
        relationTo: 'groceryEvents';
        value: number | GroceryEvent;
      } | null)
    | ({
        relationTo: 'ratings';
        value: number | Rating;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  gallery?: T;
  story?: T;
  storyMarkdown?: T;
  storyImages?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        quantity?: T;
        unit?: T;
        item?: T;
        note?: T;
        heading?: T;
        affiliateKey?: T;
        ingredient?: T;
        needsReview?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        text?: T;
        image?: T;
        timerSeconds?: T;
        uses?: T;
        id?: T;
      };
  finish?:
    | T
    | {
        storageDays?: T;
        reheat?: T;
        leftoverIdeas?: T;
      };
  videoUrl?: T;
  heroAnnotations?:
    | T
    | {
        x?: T;
        y?: T;
        kicker?: T;
        note?: T;
        id?: T;
      };
  cuisine?: T;
  course?: T;
  mainIngredient?: T;
  spiciness?: T;
  sweetness?: T;
  richness?: T;
  effort?: T;
  dietaryTags?: T;
  prepMinutes?: T;
  cookMinutes?: T;
  totalMinutes?: T;
  difficulty?: T;
  costPerServing?: T;
  equipment?: T;
  onePan?: T;
  makeAhead?: T;
  nutrition?:
    | T
    | {
        calories?: T;
        protein?: T;
        carbs?: T;
        fat?: T;
        saturates?: T;
        sugars?: T;
        fibre?: T;
        salt?: T;
        servingGrams?: T;
      };
  editorialRating?: T;
  ratingCount?: T;
  ratingSum?: T;
  ratingScore?: T;
  provenance?: T;
  author?: T;
  sourceAttribution?:
    | T
    | {
        sourceName?: T;
        sourceUrl?: T;
      };
  brandSlots?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  category?: T;
  countable?: T;
  substitutions?:
    | T
    | {
        sub?: T;
        subText?: T;
        kind?: T;
        ratio?: T;
        note?: T;
        id?: T;
      };
  densityGPerMl?: T;
  gramsPerPiece?: T;
  nutrition?:
    | T
    | {
        kcalPer100g?: T;
        proteinPer100g?: T;
        carbsPer100g?: T;
        fatPer100g?: T;
        saturatesPer100g?: T;
        sugarsPer100g?: T;
        fibrePer100g?: T;
        saltPer100g?: T;
        source?: T;
      };
  price?:
    | T
    | {
        packPrice?: T;
        packAmount?: T;
        packUnit?: T;
        source?: T;
        checkedAt?: T;
      };
  needsReview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines_select".
 */
export interface CuisinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  flagEmoji?: T;
  heroImage?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  creatorId?: T;
  handle?: T;
  verified?: T;
  avatar?: T;
  bio?: T;
  socials?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        x?: T;
        website?: T;
      };
  provenanceDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandCards_select".
 */
export interface BrandCardsSelect<T extends boolean = true> {
  brand?: T;
  logo?: T;
  creatives?:
    | T
    | {
        image?: T;
        tagline?: T;
        active?: T;
        id?: T;
      };
  productImage?: T;
  tagline?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  targetRegions?:
    | T
    | {
        code?: T;
        id?: T;
      };
  assignedCuisines?: T;
  assignedRecipes?: T;
  revSharePercent?: T;
  cpmCents?: T;
  weight?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  maxImpressions?: T;
  impressionsServed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  gallery?: T;
  story?: T;
  storyMarkdown?: T;
  storyImages?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        quantity?: T;
        unit?: T;
        item?: T;
        note?: T;
        heading?: T;
        affiliateKey?: T;
        ingredient?: T;
        needsReview?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        text?: T;
        image?: T;
        timerSeconds?: T;
        uses?: T;
        id?: T;
      };
  finish?:
    | T
    | {
        storageDays?: T;
        reheat?: T;
        leftoverIdeas?: T;
      };
  cuisine?: T;
  course?: T;
  mainIngredient?: T;
  spiciness?: T;
  sweetness?: T;
  richness?: T;
  effort?: T;
  dietaryTags?: T;
  prepMinutes?: T;
  cookMinutes?: T;
  totalMinutes?: T;
  difficulty?: T;
  costPerServing?: T;
  equipment?: T;
  onePan?: T;
  makeAhead?: T;
  nutrition?:
    | T
    | {
        calories?: T;
        protein?: T;
        carbs?: T;
        fat?: T;
        saturates?: T;
        sugars?: T;
        fibre?: T;
        salt?: T;
        servingGrams?: T;
      };
  creatorId?: T;
  creatorName?: T;
  creatorEmail?: T;
  creatorHandle?: T;
  creatorAvatar?: T;
  videoUrl?: T;
  promotedRecipe?: T;
  editsRecipe?: T;
  moderationStatus?: T;
  moderationNote?: T;
  submittedBy?: T;
  submitterEmail?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerRequests_select".
 */
export interface PartnerRequestsSelect<T extends boolean = true> {
  company?: T;
  website?: T;
  contactName?: T;
  contactEmail?: T;
  promoting?: T;
  targetRegions?:
    | T
    | {
        code?: T;
        id?: T;
      };
  budgetRange?: T;
  message?: T;
  status?: T;
  scaffoldedCard?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adEvents_select".
 */
export interface AdEventsSelect<T extends boolean = true> {
  kind?: T;
  brandCard?: T;
  recipe?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groceryRetailers_select".
 */
export interface GroceryRetailersSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  type?: T;
  countries?:
    | T
    | {
        code?: T;
        id?: T;
      };
  searchUrlTemplate?: T;
  affiliateUrlTemplate?: T;
  network?: T;
  priority?: T;
  active?: T;
  notes?: T;
  impressions?: T;
  clicks?: T;
  ctr?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groceryEvents_select".
 */
export interface GroceryEventsSelect<T extends boolean = true> {
  kind?: T;
  retailer?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ratings_select".
 */
export interface RatingsSelect<T extends boolean = true> {
  recipe?: T;
  userId?: T;
  stars?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}