/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    recipes: Recipe;
    cuisines: Cuisine;
    authors: Author;
    brandCards: BrandCard;
    media: Media;
    submissions: Submission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    cuisines: CuisinesSelect<false> | CuisinesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    brandCards: BrandCardsSelect<false> | BrandCardsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  title: string;
  /**
   * Food photography is the product. This one is not optional.
   */
  heroImage: number | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Optional, and capped at 120 words. It renders *below* the recipe — it must never block the cook.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  servings: number;
  ingredients: {
    quantity?: string | null;
    unit?: string | null;
    item: string;
    /**
     * e.g. "finely diced", "room temperature"
     */
    note?: string | null;
    /**
     * Optional key linking this ingredient to an affiliate product. Phase 1 stores it; Phase 2 resolves it.
     */
    affiliateKey?: string | null;
    id?: string | null;
  }[];
  steps: {
    text: string;
    image?: (number | null) | Media;
    /**
     * Optional. Renders an inline timer for this step.
     */
    timerSeconds?: number | null;
    id?: string | null;
  }[];
  /**
   * Optional. Shown on cooking mode’s finish screen — storage, reheating, and what the leftovers become.
   */
  finish?: {
    /**
     * Days it keeps refrigerated.
     */
    storageDays?: number | null;
    /**
     * e.g. "Low heat with a splash of water."
     */
    reheat?: string | null;
    /**
     * What tomorrow’s lunch becomes.
     */
    leftoverIdeas?: string | null;
  };
  /**
   * Optional. A creator’s TikTok/YouTube/Reels/Vimeo link — embedded on the recipe page. Set automatically when a creator submission is approved.
   */
  videoUrl?: string | null;
  cuisine: number | Cuisine;
  course: 'breakfast' | 'lunch' | 'dinner' | 'side' | 'snack' | 'dessert';
  /**
   * What the dish is built on — the shopping-list headline.
   */
  mainIngredient:
    | 'chicken'
    | 'beef'
    | 'pork'
    | 'lamb'
    | 'seafood'
    | 'eggs'
    | 'tofu-tempeh'
    | 'legumes'
    | 'vegetables'
    | 'rice-grains'
    | 'pasta-noodles'
    | 'cheese-dairy'
    | 'duck'
    | 'turkey'
    | 'mushrooms'
    | 'potatoes'
    | 'bread-dough'
    | 'chocolate-sweets'
    | 'fruit'
    | 'squash-pumpkin'
    | 'corn-maize'
    | 'plantains-cassava';
  /**
   * 0 = No heat, 5 = Fiery
   */
  spiciness: number;
  /**
   * 0 = Savoury, 5 = Dessert-sweet
   */
  sweetness: number;
  /**
   * 0 = Clean, 5 = Decadent
   */
  richness: number;
  /**
   * 0 = Effortless, 5 = A project
   */
  effort: number;
  dietaryTags?:
    | (
        | 'vegan'
        | 'vegetarian'
        | 'pescatarian'
        | 'gluten-free'
        | 'dairy-free'
        | 'nut-free'
        | 'egg-free'
        | 'low-carb'
        | 'keto'
        | 'paleo'
        | 'whole30'
        | 'halal'
        | 'kosher'
        | 'low-fodmap'
        | 'sugar-free'
        | 'high-protein'
        | 'low-sodium'
        | 'soy-free'
        | 'shellfish-free'
      )[]
    | null;
  prepMinutes: number;
  cookMinutes: number;
  /**
   * Derived from prep + cook.
   */
  totalMinutes?: number | null;
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * US cents per serving, from the import pipeline. Blank = unknown. Powers the student budget features.
   */
  costPerServing?: number | null;
  /**
   * Optional. Feeds Recipe JSON-LD when present.
   */
  nutrition?: {
    calories?: number | null;
    /**
     * grams
     */
    protein?: number | null;
    /**
     * grams
     */
    carbs?: number | null;
    /**
     * grams
     */
    fat?: number | null;
  };
  /**
   * Load-bearing (§3): drives trust badges, filtering, and Google transparency.
   */
  provenance: 'authored' | 'community' | 'api-imported';
  author: number | Author;
  /**
   * Required for api-imported recipes — imported content is duplicate content across the web and must carry canonical attribution (§3, §8).
   */
  sourceAttribution?: {
    sourceName?: string | null;
    sourceUrl?: string | null;
  };
  /**
   * Optional direct assignment. Cards can also become eligible via their own cuisine/recipe targeting.
   */
  brandSlots?: (number | BrandCard)[] | null;
  /**
   * Falls back to the recipe title.
   */
  metaTitle?: string | null;
  /**
   * Falls back to the first line of the story.
   */
  metaDescription?: string | null;
  /**
   * Falls back to the hero image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically on first publish.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the dish for screen readers and for Google Images.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source. Required for anything not shot in-house.
   */
  credit?: string | null;
  license?: ('original' | 'licensed' | 'ai-generated' | 'partner') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines".
 */
export interface Cuisine {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  region:
    | 'east-asia'
    | 'south-asia'
    | 'southeast-asia'
    | 'middle-east'
    | 'africa'
    | 'northern-europe'
    | 'southern-europe'
    | 'eastern-europe'
    | 'north-america'
    | 'latin-america'
    | 'caribbean'
    | 'oceania'
    | 'cross-regional';
  /**
   * Optional. Used as a lightweight glyph where a hero image would be too heavy.
   */
  flagEmoji?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * One or two sentences. Doubles as the cuisine hub meta description.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Changing this changes the public URL.
   */
  slug: string;
  /**
   * Supabase user id — the stable key that ties a creator to their profile.
   */
  creatorId?: string | null;
  /**
   * Public @handle shown on recipes and the creator profile.
   */
  handle?: string | null;
  /**
   * Editorial trust mark — grant manually once you know the creator is real.
   */
  verified?: boolean | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * Provenance applied to new recipes by this author unless overridden on the recipe itself.
   */
  provenanceDefault: 'authored' | 'community' | 'api-imported';
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-curated partner placements. Swapping a card in or out is a CMS edit — rotation stays fair automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandCards".
 */
export interface BrandCard {
  id: number;
  brand: string;
  logo?: (number | null) | Media;
  productImage?: (number | null) | Media;
  /**
   * One line. This is a card, not a banner.
   */
  tagline: string;
  ctaLabel: string;
  /**
   * Affiliate or partner destination. Rendered with rel="sponsored nofollow".
   */
  ctaUrl: string;
  /**
   * ISO country codes (GB, US, DE…). Leave empty to target globally.
   */
  targetRegions?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Card is eligible on any recipe in these cuisines.
   */
  assignedCuisines?: (number | Cuisine)[] | null;
  /**
   * Card is eligible on these specific recipes.
   */
  assignedRecipes?: (number | Recipe)[] | null;
  /**
   * Relative share of impressions in the rotation. 2 is shown twice as often as 1. 0 disables without deactivating.
   */
  weight: number;
  active?: boolean | null;
  /**
   * Optional. Card is ineligible before this moment.
   */
  startsAt?: string | null;
  /**
   * Optional. Card is ineligible after this moment.
   */
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Creator submissions from /studio. Approve to publish; promotion is automatic.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title: string;
  /**
   * Food photography is the product. This one is not optional.
   */
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Optional, and capped at 120 words. It renders *below* the recipe — it must never block the cook.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  servings: number;
  ingredients: {
    quantity?: string | null;
    unit?: string | null;
    item: string;
    /**
     * e.g. "finely diced", "room temperature"
     */
    note?: string | null;
    /**
     * Optional key linking this ingredient to an affiliate product. Phase 1 stores it; Phase 2 resolves it.
     */
    affiliateKey?: string | null;
    id?: string | null;
  }[];
  steps: {
    text: string;
    image?: (number | null) | Media;
    /**
     * Optional. Renders an inline timer for this step.
     */
    timerSeconds?: number | null;
    id?: string | null;
  }[];
  /**
   * Optional. Shown on cooking mode’s finish screen — storage, reheating, and what the leftovers become.
   */
  finish?: {
    /**
     * Days it keeps refrigerated.
     */
    storageDays?: number | null;
    /**
     * e.g. "Low heat with a splash of water."
     */
    reheat?: string | null;
    /**
     * What tomorrow’s lunch becomes.
     */
    leftoverIdeas?: string | null;
  };
  cuisine: number | Cuisine;
  course: 'breakfast' | 'lunch' | 'dinner' | 'side' | 'snack' | 'dessert';
  /**
   * What the dish is built on — the shopping-list headline.
   */
  mainIngredient:
    | 'chicken'
    | 'beef'
    | 'pork'
    | 'lamb'
    | 'seafood'
    | 'eggs'
    | 'tofu-tempeh'
    | 'legumes'
    | 'vegetables'
    | 'rice-grains'
    | 'pasta-noodles'
    | 'cheese-dairy'
    | 'duck'
    | 'turkey'
    | 'mushrooms'
    | 'potatoes'
    | 'bread-dough'
    | 'chocolate-sweets'
    | 'fruit'
    | 'squash-pumpkin'
    | 'corn-maize'
    | 'plantains-cassava';
  /**
   * 0 = No heat, 5 = Fiery
   */
  spiciness: number;
  /**
   * 0 = Savoury, 5 = Dessert-sweet
   */
  sweetness: number;
  /**
   * 0 = Clean, 5 = Decadent
   */
  richness: number;
  /**
   * 0 = Effortless, 5 = A project
   */
  effort: number;
  dietaryTags?:
    | (
        | 'vegan'
        | 'vegetarian'
        | 'pescatarian'
        | 'gluten-free'
        | 'dairy-free'
        | 'nut-free'
        | 'egg-free'
        | 'low-carb'
        | 'keto'
        | 'paleo'
        | 'whole30'
        | 'halal'
        | 'kosher'
        | 'low-fodmap'
        | 'sugar-free'
        | 'high-protein'
        | 'low-sodium'
        | 'soy-free'
        | 'shellfish-free'
      )[]
    | null;
  prepMinutes: number;
  cookMinutes: number;
  /**
   * Derived from prep + cook.
   */
  totalMinutes?: number | null;
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * US cents per serving, from the import pipeline. Blank = unknown. Powers the student budget features.
   */
  costPerServing?: number | null;
  /**
   * Optional. Feeds Recipe JSON-LD when present.
   */
  nutrition?: {
    calories?: number | null;
    /**
     * grams
     */
    protein?: number | null;
    /**
     * grams
     */
    carbs?: number | null;
    /**
     * grams
     */
    fat?: number | null;
  };
  /**
   * Supabase user id of the creator who submitted this.
   */
  creatorId?: string | null;
  creatorName?: string | null;
  creatorEmail?: string | null;
  creatorHandle?: string | null;
  /**
   * The creator’s account avatar at submission time.
   */
  creatorAvatar?: (number | null) | Media;
  /**
   * Optional TikTok/YouTube/Reels link — creators are video-first.
   */
  videoUrl?: string | null;
  /**
   * Set automatically when approved.
   */
  promotedRecipe?: (number | null) | Recipe;
  moderationStatus: 'pending' | 'approved' | 'rejected';
  /**
   * Populated once community accounts exist.
   */
  submittedBy?: (number | null) | User;
  /**
   * Contact for the submitter before accounts exist.
   */
  submitterEmail?: string | null;
  /**
   * Internal. Why this was approved or rejected.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'cuisines';
        value: number | Cuisine;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'brandCards';
        value: number | BrandCard;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  gallery?: T;
  story?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        quantity?: T;
        unit?: T;
        item?: T;
        note?: T;
        affiliateKey?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        text?: T;
        image?: T;
        timerSeconds?: T;
        id?: T;
      };
  finish?:
    | T
    | {
        storageDays?: T;
        reheat?: T;
        leftoverIdeas?: T;
      };
  videoUrl?: T;
  cuisine?: T;
  course?: T;
  mainIngredient?: T;
  spiciness?: T;
  sweetness?: T;
  richness?: T;
  effort?: T;
  dietaryTags?: T;
  prepMinutes?: T;
  cookMinutes?: T;
  totalMinutes?: T;
  difficulty?: T;
  costPerServing?: T;
  nutrition?:
    | T
    | {
        calories?: T;
        protein?: T;
        carbs?: T;
        fat?: T;
      };
  provenance?: T;
  author?: T;
  sourceAttribution?:
    | T
    | {
        sourceName?: T;
        sourceUrl?: T;
      };
  brandSlots?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines_select".
 */
export interface CuisinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  flagEmoji?: T;
  heroImage?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  creatorId?: T;
  handle?: T;
  verified?: T;
  avatar?: T;
  bio?: T;
  provenanceDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandCards_select".
 */
export interface BrandCardsSelect<T extends boolean = true> {
  brand?: T;
  logo?: T;
  productImage?: T;
  tagline?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  targetRegions?:
    | T
    | {
        code?: T;
        id?: T;
      };
  assignedCuisines?: T;
  assignedRecipes?: T;
  weight?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  gallery?: T;
  story?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        quantity?: T;
        unit?: T;
        item?: T;
        note?: T;
        affiliateKey?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        text?: T;
        image?: T;
        timerSeconds?: T;
        id?: T;
      };
  finish?:
    | T
    | {
        storageDays?: T;
        reheat?: T;
        leftoverIdeas?: T;
      };
  cuisine?: T;
  course?: T;
  mainIngredient?: T;
  spiciness?: T;
  sweetness?: T;
  richness?: T;
  effort?: T;
  dietaryTags?: T;
  prepMinutes?: T;
  cookMinutes?: T;
  totalMinutes?: T;
  difficulty?: T;
  costPerServing?: T;
  nutrition?:
    | T
    | {
        calories?: T;
        protein?: T;
        carbs?: T;
        fat?: T;
      };
  creatorId?: T;
  creatorName?: T;
  creatorEmail?: T;
  creatorHandle?: T;
  creatorAvatar?: T;
  videoUrl?: T;
  promotedRecipe?: T;
  moderationStatus?: T;
  submittedBy?: T;
  submitterEmail?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}